#!/bin/bash
#user 1 must be 18+ years 
#All movies can be shown on user1 screen
#there are no restriction because user1 is of age
#no restrictions should be placed on this account
#account should be renewed monthly
#free for all other users
