#!/bin/bash
#user2 should be up to 13+ to access
#there should be some parental guide and restriction for user2
#user2 should have parental guide
#user2 should be able to access gaming
#user2 should  create a password
